/* ============================================================
   Base de conhecimento real — Clínica Dra. Fernanda Cristófoli
   Método: Acolher · Conectar · Ancorar · Convidar
   Derivado do Playbook de Atendimento e do Relatório de Conversas.
   ============================================================ */
window.KB = {
  clinic: {
    name: "Clínica Fernanda Cristófoli",
    tagline: "Beleza com elegância e naturalidade",
    whatsapp: "(48) 9 9167-2097",
    local: "Florianópolis, bairro Estreito",
    parcelamento: "até 5x sem juros no cartão (apenas quando perguntarem)",
  },

  /* As quatro etapas de toda conversa que vira agendamento. */
  metodo: [
    { etapa: "Acolher", resumo: "Antes de qualquer palavra sobre procedimento, leia o lead, use o nome certo e responda rápido. Cada pessoa chega num estado emocional diferente." },
    { etapa: "Conectar", resumo: "Abra espaço para ela falar de si com uma pergunta sobre desejo, nunca sobre defeito. Conexão vem antes de informação." },
    { etapa: "Ancorar", resumo: "Construa valor com o processo da Dra. Fernanda antes do número. Um procedimento por vez, valor cheio, nunca a tabela toda." },
    { etapa: "Convidar", resumo: "A avaliação é a venda real, não o procedimento. Quem entra no consultório fecha. Convide com uma escolha simples." },
  ],

  /* --- Tratamentos (preços reais quando disponíveis) ------ */
  treatments: [
    {
      id: "toxina",
      name: "Toxina Botulínica (Botox)",
      promise: "A arte de suavizar o tempo.",
      detail: "A Dra. Fernanda avalia a musculatura específica antes de aplicar, por isso o resultado fica preciso e natural.",
      faixa: "a partir de R$ 1.350 (terço superior)",
      duracao: "efeito de 4 a 6 meses",
      bestFor: "linhas da testa, glabela, olhos, prevenção",
    },
    {
      id: "labial",
      name: "Preenchimento Labial",
      promise: "A moldura perfeita para o sorriso.",
      detail: "Realça o volume e o contorno respeitando o formato natural da boca.",
      faixa: "a partir de R$ 1.500",
      duracao: "efeito de 8 a 12 meses",
      bestFor: "lábios finos, contorno indefinido, volume natural",
    },
    {
      id: "bioestimulador",
      name: "Bioestimulador de Colágeno",
      promise: "A fundação da firmeza.",
      detail: "Restaura a sustentação da face de dentro para fora. Costuma ser o ponto de partida em casos de flacidez e pós-emagrecimento.",
      faixa: "a partir de R$ 2.200",
      duracao: "protocolo de 2 a 3 sessões",
      bestFor: "flacidez, perda de firmeza, pós-emagrecimento",
    },
    {
      id: "harmonizacao",
      name: "Harmonização Facial",
      promise: "Equilíbrio entre proporção e naturalidade.",
      detail: "Plano completo da face, desenhado sob medida na avaliação. Não é um procedimento isolado.",
      faixa: "plano personalizado, definido na avaliação",
      duracao: "resultado progressivo, manutenção anual",
      bestFor: "quem busca um plano completo de rejuvenescimento",
    },
    {
      id: "microagulhamento",
      name: "Microagulhamento",
      promise: "Regeneração profunda da pele.",
      detail: "Infusão de ativos e melhora de textura, viço e cicatrizes.",
      faixa: "sob avaliação",
      duracao: "protocolo de 3 a 4 sessões",
      bestFor: "textura irregular, cicatrizes de acne, viço",
    },
    {
      id: "peeling",
      name: "Peeling Químico",
      promise: "Renovação e luminosidade.",
      detail: "Uniformiza o tom e devolve o brilho da pele.",
      faixa: "sob avaliação",
      duracao: "protocolo conforme objetivo",
      bestFor: "manchas, melasma, falta de luminosidade",
    },
  ],

  /* --- Cenários curados (resposta instantânea) ------------ */
  scenarios: [
    {
      id: "abordagem",
      title: "Como abrir o primeiro contato",
      tags: ["primeiro contato", "como começar", "comecar", "abrir", "abordagem", "saudação", "primeira mensagem", "como falar", "interesse", "mais informações", "informacoes"],
      leitura: "A primeira mensagem acolhe antes de qualquer pergunta de procedimento. Use o nome do WhatsApp, leia o que a pessoa escreveu e abra espaço para ela falar do desejo. Nunca nomeie o problema (rugas, flacidez) antes que ela mesma traga.",
      conducao: "Oi, [nome]! Fico feliz que você entrou em contato. 🌷 Me chamo [seu nome], faço parte da equipe da Dra. Fernanda. Me conta, o que te chamou atenção pra falar com a gente?",
      passos: [
        "Responda rápido, idealmente em minutos.",
        "Use o nome do WhatsApp e confira se está certo.",
        "Abra com pergunta sobre desejo, não sobre defeito.",
        "Deixe ela falar antes de qualquer informação.",
      ],
      objecao: "Nunca pergunte 'o que te incomoda no seu rosto?'. Isso força autodiagnóstico. Prefira 'o que você está pensando em cuidar?'.",
      tratamento: null,
    },
    {
      id: "preco",
      title: "Cliente pede o preço de um procedimento",
      tags: ["preço", "preco", "valor", "quanto custa", "quanto é", "quanto e", "botox", "preenchimento", "orçamento", "orcamento", "tabela", "quanto está", "quanto esta"],
      leitura: "Preço sem contexto vira só um número para comparar com a clínica ao lado. Quase nunca a venda se perde por preço real, e sim por conexão que não veio antes do número. Ancore o valor no processo da Dra. Fernanda e convide para a avaliação. Dê o valor cheio, nunca em parcelas.",
      conducao: "Oi, [nome]! O botox aqui começa em R$ 1.350 no terço superior. O que a Dra. Fernanda faz diferente é avaliar a sua musculatura específica antes de aplicar qualquer coisa, por isso o resultado fica tão preciso e natural. Vale muito uma avaliação com ela pra você ver como ela trabalha. Tem horário essa semana: você prefere manhã ou tarde?",
      passos: [
        "Ancore o valor no processo da Dra. antes do número.",
        "Dê o valor cheio, nunca em parcelas.",
        "Um procedimento por vez, nunca a tabela toda.",
        "Convide para a avaliação com uma escolha simples: manhã ou tarde?",
      ],
      objecao: "Se perguntar sobre parcelamento depois do valor: 'Parcelamos em até 5x sem juros no cartão.' Simples, sem elaborar. Nunca ofereça antes de ser perguntada, e nunca apresente o preço já parcelado.",
      tratamento: "toxina",
    },
    {
      id: "avaliando",
      title: "Cliente diz que vai pensar ou está avaliando",
      tags: ["vou pensar", "avaliando", "pensar", "depois", "te falo", "outro momento", "mais pra frente", "deixar para", "vou ver", "obrigada pelas informações"],
      leitura: "'Vou pensar' raramente é sobre pensar. É uma objeção educada que esconde dúvida de momento, de valor ou de confiança. Não encerre nem pressione. Pergunte com leveza qual foi o motivo real e peça permissão para retomar mais pra frente.",
      conducao: "Fica tranquila, sem pressão nenhuma. 🤍 Posso te perguntar só uma coisa? Foi mais uma questão de momento agora ou ficou alguma dúvida sobre os procedimentos?",
      passos: [
        "Acolha sem drama e sem insistir.",
        "Pergunte o motivo real: momento ou dúvida.",
        "Se for momento, peça permissão: 'posso te chamar mais pra frente?'",
        "Anote nome, data e o desejo que ela demonstrou para a reativação.",
      ],
      objecao: "Nunca repita a oferta nem ligue de surpresa. Se ela liberar o contato futuro, reabra depois com algo específico ligado ao desejo dela, nunca com 'oi, sumiu de mim'.",
      tratamento: null,
    },
    {
      id: "silencio",
      title: "O lead sumiu e parou de responder",
      tags: ["sumiu", "não respondeu", "nao respondeu", "silêncio", "silencio", "parou de responder", "follow up", "follow-up", "retomar", "não respondeu mais", "ficou sem resposta"],
      leitura: "O silêncio encerra só o primeiro ciclo, não a conversa. O erro clássico é repetir a mesma pergunta e mandar várias mensagens seguidas. Mude o ângulo a cada contato e use resultados relevantes, sem cobrar resposta.",
      conducao: "Oi, [nome]! Separei um resultado aqui da Dra. Fernanda que achei que você ia gostar de ver. Qualquer dúvida é só me chamar. 🌷",
      passos: [
        "Nunca repita a pergunta que não foi respondida.",
        "24h depois: um resultado relevante ou uma pergunta diferente.",
        "15 e 45 dias: pontos de contato leves, sem cobrar resposta.",
        "90 dias: novidade ligada ao desejo que ela demonstrou.",
      ],
      objecao: "Nunca mande mais de duas mensagens seguidas sem resposta. Volume não substitui mudança de ângulo.",
      tratamento: null,
    },
    {
      id: "historia",
      title: "A pessoa chega contando uma história",
      tags: ["emagrecimento", "emagreci", "mudou", "derretimento", "flácido", "flacida", "flacidez", "jornada", "autoestima", "história", "historia", "desabafo", "parto", "depois que"],
      leitura: "Esse é o lead mais valioso e o mais fácil de perder por frieza. Ela não está pedindo informação, está se abrindo. Reconheça a jornada antes de qualquer pergunta clínica. Só depois conduza para a experiência anterior e a avaliação.",
      conducao: "Posso só imaginar a jornada que deve estar sendo pra você. 💛 É bem recorrente aqui no consultório da Dra. Fernanda esse tipo de queixa, e os resultados são realmente bonitos. Me conta: você já chegou a fazer algum procedimento no rosto antes?",
      passos: [
        "Acolha a história com empatia genuína primeiro.",
        "Não vá direto ao preço nem ao procedimento.",
        "Pergunte sobre experiências anteriores para diferenciar.",
        "Apresente um procedimento de entrada, não a tabela toda.",
      ],
      objecao: "Se ela citar vários procedimentos, não some tudo, porque passa de R$ 5.000 e ela recua. Indique um ponto de partida, como o bioestimulador, e diga que o resto a Dra. avalia depois.",
      tratamento: "bioestimulador",
    },
    {
      id: "fora-perfil",
      title: "Contato fora do perfil da clínica",
      tags: ["convênio", "convenio", "plano de saúde", "plano", "sc saúde", "sc saude", "couro cabeludo", "cabelo", "não é no rosto", "nao e no rosto", "outro serviço", "atende plano"],
      leitura: "Quando o contato claramente não é do perfil (convênio, outro serviço), não force qualificação nem redirecione para algo que não existe. Encerre com gentileza e brevidade, deixando a porta aberta. Nunca apague mensagens.",
      conducao: "Boa tarde, [nome]! Não atendemos convênio. A Dra. Fernanda atua com harmonização facial, sempre em particular. Se um dia você quiser cuidar do rosto, a gente fica à disposição! 🌷",
      passos: [
        "Identifique cedo que está fora do perfil.",
        "Encerre com gentileza em uma única mensagem.",
        "Não ative o script de qualificação.",
        "Nunca apague mensagens; se errou, corrija na próxima.",
      ],
      objecao: "Nada de gastar energia tentando converter quem não é do perfil. Gentileza e porta aberta bastam.",
      tratamento: null,
    },
    {
      id: "para-outra-pessoa",
      title: "Está pesquisando para outra pessoa",
      tags: ["minha mãe", "minha mae", "para minha", "pra minha", "presente", "para ela", "marido", "filha", "esposa", "pesquisando para", "é para a"],
      leitura: "Quem pesquisa para outra pessoa age por carinho. Reconheça esse gesto, descubra a experiência anterior de quem vai fazer e conduza para a avaliação dessa pessoa, sem catálogo genérico de fotos.",
      conducao: "Que carinhoso você pesquisar isso pra ela. 💛 Me conta: quando ela fez antes, ela ficou satisfeita com o resultado ou sentiu que poderia ter ficado melhor?",
      passos: [
        "Valorize o cuidado de quem está pesquisando.",
        "Pergunte sobre a experiência anterior da pessoa.",
        "Conecte qualquer resultado ao perfil dela, nunca como catálogo.",
        "Convide a pessoa que vai fazer para a avaliação.",
      ],
      objecao: "Se pedir o valor direto, ancore no processo da Dra. e dê o valor cheio, depois convide para a avaliação dela.",
      tratamento: "toxina",
    },
    {
      id: "procedimento-especifico",
      title: "Já sabe o que quer e está comparando",
      tags: ["já pesquisei", "ja pesquisei", "comparando", "qual a diferença", "por que vocês", "por que voces", "já sei", "decidida", "quero fazer", "qual o diferencial"],
      leitura: "Esse lead já entende o procedimento. Ela não precisa de aula, precisa de uma razão para escolher a Dra. Fernanda. Mostre o diferencial (avaliação antes da aplicação, resultado personalizado) e convide para sentir isso na avaliação.",
      conducao: "Oi, [nome]! Esse é um dos procedimentos preferidos das nossas pacientes. 💫 O que a Dra. Fernanda faz diferente é avaliar o seu rosto antes de qualquer aplicação, pra o resultado ser preciso e natural pra você. Vale muito conhecer na avaliação. Você prefere manhã ou tarde?",
      passos: [
        "Não eduque demais: ela já sabe o que quer.",
        "Mostre o diferencial da Dra., não marcas e laboratórios.",
        "Conecte resultados ao perfil dela.",
        "Convide para a avaliação com escolha simples.",
      ],
      objecao: "Evite listar marcas de produto para se defender do preço. Isso sinaliza insegurança. O diferencial é o cuidado da Dra., não o rótulo do laboratório.",
      tratamento: "harmonizacao",
    },
    {
      id: "demora",
      title: "Demorei a responder e o lead esfriou",
      tags: ["demora", "demorei", "fim de semana", "atrasado", "esfriou", "sábado", "sabado", "domingo", "horas depois", "demorou"],
      leitura: "Lead que chega no impulso e espera horas já mudou de estado emocional. Reconheça a demora sem drama, use o nome certo e reabra com uma pergunta leve, nunca com diagnóstico de problema.",
      conducao: "Oi, [nome]! Bom dia. Desculpa a demora em responder, o fim de semana correu por aqui. 🌿 Me chamo [seu nome], faço parte da equipe da Dra. Fernanda. Me conta: o que te chamou atenção pra falar com a gente?",
      passos: [
        "Reconheça a demora com leveza, sem se justificar demais.",
        "Use o nome do WhatsApp e confira antes de enviar.",
        "Reabra com pergunta leve sobre o desejo.",
        "Responda o quanto antes a partir de agora.",
      ],
      objecao: "Nunca finja que nada aconteceu nem mande o script padrão. O reconhecimento sincero da demora reabre a conversa.",
      tratamento: null,
    },
    {
      id: "medo-artificial",
      title: "Tem medo de ficar artificial ou exagerada",
      tags: ["artificial", "exagero", "natural", "medo", "estranho", "exagerado", "fake", "pato", "cara de", "vai ficar bom"],
      leitura: "O medo de ficar artificial é medo de perder a própria identidade. Acolha e reforce a filosofia da Dra. Fernanda: o resultado é sempre natural, pensado para cada rosto. Nunca crie a objeção sozinha dizendo 'sem exageros' antes de ela trazer o medo.",
      conducao: "Fico feliz que você pense assim, porque é exatamente a filosofia da Dra. Fernanda. 🌿 O objetivo nunca é te transformar em outra pessoa, e sim revelar a sua melhor versão, com naturalidade. O resultado é você, descansada e no seu melhor.",
      passos: [
        "Acolha o medo antes de responder.",
        "Reforce a naturalidade como assinatura da Dra.",
        "Não antecipe a objeção: só fale de exagero se ela falar primeiro.",
        "Convide para a avaliação como espaço seguro.",
      ],
      objecao: "Se citar um resultado ruim que viu por aí: 'aquilo costuma ser excesso sem planejamento. Aqui a Dra. avalia cada rosto antes, justamente pra isso não acontecer.'",
      tratamento: "toxina",
    },
  ],

  /* --- Personas reais para o modo Treinar ---------------- */
  personas: [
    {
      id: "mayara",
      name: "Mayara",
      perfil: "Procedimento específico, preenchimento labial",
      humor: "Veio no impulso, sem vocabulário técnico",
      abertura: "Oii quanto está o preenchimento labial?",
      objetivo: "Ancorar o valor com contexto e fazer uma pergunta simples, sem termos técnicos como contorno ou volume.",
    },
    {
      id: "melissa",
      name: "Melissa",
      perfil: "Lead com história, pós-emagrecimento",
      humor: "Quer ser vista antes de ser atendida",
      abertura: "Tive um emagrecimento muito grande e senti que meu rosto mudou, está com aspecto de derretimento. Queria saber o investimento para bioestimulador, botox e ácido hialurônico.",
      objetivo: "Acolher a jornada antes de qualquer pergunta clínica e apresentar um procedimento de entrada, não a tabela toda.",
    },
    {
      id: "karolina",
      name: "Karolina",
      perfil: "Pesquisando botox para a mãe",
      humor: "Objetiva, pergunta o preço direto",
      abertura: "Bom dia! Qual o valor da consulta para botox?",
      objetivo: "Descobrir que é para a mãe, valorizar o cuidado e ancorar o preço cheio, sem parcelar.",
    },
    {
      id: "anne",
      name: "Anne",
      perfil: "Lead genérico, veio de anúncio",
      humor: "Mandou mensagem no impulso e some fácil",
      abertura: "Olá! Tenho interesse e gostaria de mais informações.",
      objetivo: "Acolher e abrir espaço com uma pergunta leve, sem perguntar o que incomoda.",
    },
    {
      id: "cirineu",
      name: "Cirineu",
      perfil: "Fora do perfil, procura convênio",
      humor: "Não conhece a clínica",
      abertura: "Boa tarde. Vocês atendem pelo plano SC Saúde?",
      objetivo: "Encerrar com gentileza em uma mensagem, sem ativar o script de qualificação.",
    },
  ],

  /* --- Guia de estudo: temas pelo método real ------------ */
  topics: [
    {
      id: "acolher",
      label: "Acolher e conectar",
      desc: "O primeiro contato, a conexão antes da informação e o que fazer quando a demora esfriou o lead.",
      scenarios: ["abordagem", "historia", "demora"],
    },
    {
      id: "ancorar",
      label: "Ancorar o valor",
      desc: "Como apresentar o preço com contexto, diferenciar a Dra. e conduzir quem já sabe o que quer.",
      scenarios: ["preco", "procedimento-especifico", "para-outra-pessoa"],
    },
    {
      id: "convidar",
      label: "Convidar e contornar objeções",
      desc: "A indecisão do 'vou pensar' e o medo de ficar artificial, sempre sem pressão.",
      scenarios: ["avaliando", "medo-artificial"],
    },
    {
      id: "silencio",
      label: "Quando o lead some",
      desc: "O protocolo de reativação que muda o ângulo a cada contato.",
      scenarios: ["silencio"],
    },
    {
      id: "perfil",
      label: "Fora do perfil",
      desc: "Como encerrar com elegância quem não é o público da clínica.",
      scenarios: ["fora-perfil"],
    },
  ],

  /* --- Sugestões de partida para o composer -------------- */
  starters: [
    "Cliente perguntou o valor do botox",
    "Ela disse que vai avaliar e me retorna depois",
    "O lead sumiu e não respondeu mais",
    "Ela contou que emagreceu e o rosto mudou",
    "Está pesquisando botox para a mãe",
    "Perguntou se a gente atende convênio",
  ],
};
